---
title: "Exp12"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(Rcmdr)
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
trialnum <- 80
subs <- dir(path = "./Exp12")
subs <- mixedsort(subs)
datall <- data.frame()
for (i in 1:length(subs))
{
  dat <- read.table(paste0("./Exp12/",subs[i]), header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", 
  strip.white=TRUE)
  dat <- dat[1:trialnum,c(2:4,6,7)]
  datall <- rbind(datall,cbind(rep(i,nrow(dat)),dat))
}
names(datall) <- c("Sub","m1","Pos","Ori","Com","Judge")
subjectfinal <- ddply(datall,c("Sub","m1"),summarise,sub_com=mean(Com),sub_judge=mean(Judge))
datfinal <- ddply(subjectfinal,"m1",summarise,feel=mean(sub_com),judgment=mean(sub_judge),feel_se=sd(sub_com)/sqrt(length(subs)),judgment_se=sd(sub_judge)/sqrt(length(subs)))
```

```{r}
sta <- subjectfinal
sta$HorR <- as.factor(sta$HorR)
sta$Sub <- as.factor(sta$Sub)
fit1 <- ezANOVA(data = sta,
               dv = sub_com,
               wid = Sub,
               within = .(HorR))
print(fit1)

fit2 <- ezANOVA(data = sta,
               dv = sub_judge,
               wid = Sub,
               within = .(HorR))
print(fit2)

fit1_1 <- subset(subjectfinal,HorR==0)
fit1_2 <- subset(subjectfinal,HorR==1)
model1 <- t.test(fit1_1$sub_com,fit1_2$sub_com,paired = TRUE)
es1 <- lsr::cohensD(x=fit1_1$sub_com,y=fit1_2$sub_com,method="paired")
model1

fit2_1 <- subset(subjectfinal,HorR==0)
fit2_2 <- subset(subjectfinal,HorR==1)
model2 <- t.test(fit2_1$sub_judge,fit2_2$sub_judge,paired = TRUE)
es2 <- lsr::cohensD(x=fit2_1$sub_judge,y=fit2_2$sub_judge,method="paired")
model2
```