---
title: "Exp10"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(Rcmdr)
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
trialnum <- 80
subs <- dir(path = "./Exp10")
subs <- mixedsort(subs)
datall <- data.frame()
for (i in 1:length(subs))
{
  dat <- readXL(paste0("./Exp10/",subs[i]),
   rownames=FALSE, header=TRUE, na="", sheet="Sheet1", stringsAsFactors=TRUE)
  dat <- dat[1:trialnum,c(2:4,6,7)]
  datall <- rbind(datall,cbind(rep(i+21,nrow(dat)),dat))
}
names(datall) <- c("Sub","Pos","Ori","m","Com","Judge")
subjectfinal <- ddply(datall,c("Sub","m"),summarise,sub_com=mean(Com),sub_judge=mean(Judge))
datfinal <- ddply(subjectfinal,"m",summarise,feel=mean(sub_com),judgment=mean(sub_judge),feel_se=sd(sub_com)/sqrt(25),judgment_se=sd(sub_judge)/sqrt(25))
```

```{r}
sta <- subjectfinal
sta$HorR <- as.factor(sta$HorR)
sta$Sub <- as.factor(sta$Sub)
fit1 <- ezANOVA(data = sta,
               dv = sub_com,
               wid = Sub,
               within = .(HorR))
print(fit1)

fit2 <- ezANOVA(data = sta,
               dv = sub_judge,
               wid = Sub,
               within = .(HorR))
print(fit2)

fit1_1 <- subset(subjectfinal,HorR==0)
fit1_2 <- subset(subjectfinal,HorR==1)
model1 <- t.test(fit1_1$sub_com,fit1_2$sub_com,paired = TRUE)
es1 <- lsr::cohensD(x=fit1_1$sub_com,y=fit1_2$sub_com,method="paired")
model1

fit2_1 <- subset(subjectfinal,HorR==0)
fit2_2 <- subset(subjectfinal,HorR==1)
model2 <- t.test(fit2_1$sub_judge,fit2_2$sub_judge,paired = TRUE)
es2 <- lsr::cohensD(x=fit2_1$sub_judge,y=fit2_2$sub_judge,method="paired")
model2
```

```{r}
ggplot(data = datfinal,aes(x=m,y=feel)) + geom_point(size=2) + geom_line(size=1) + geom_errorbar(aes(ymin=feel-feel_se, ymax=feel+feel_se), width=0.15,size=1) + ylab("Subjective rating") + xlab("Value of parameter m")+ coord_cartesian(xlim=c(0,8),ylim=c(1, 5)) + scale_y_continuous(breaks=seq(1, 5, 1),expand=c(0,0)) + scale_x_continuous(breaks=seq(0, 8, 1)) + theme_bw() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_blank(),
  legend.position = c(0.9,0.85),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
```

```{r}
ggplot(data = subjectfinal,aes(x=m,y=sub_com)) + geom_point(size=2) + geom_line(size=1) + ylab("Subjective rating") + xlab("Value of parameter m")+ coord_cartesian(xlim=c(0,8),ylim=c(1, 5)) + scale_y_continuous(breaks=seq(1, 5, 1),expand=c(0,0)) + scale_x_continuous(breaks=seq(0, 8, 1)) + theme_bw() + facet_wrap(~Sub) + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_blank(),
  legend.position = c(0.9,0.85),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
```

```{r}
ggplot(data = datfinal,aes(x=m,y=judgment)) + geom_point(size=2) + geom_line(size=1) + geom_errorbar(aes(ymin=judgment-judgment_se, ymax=judgment+judgment_se), width=0.15,size=1) + ylab("Probability of being judged as human") + xlab("Value of parameter m")+ coord_cartesian(xlim=c(0,8),ylim=c(0, 1)) + scale_y_continuous(breaks=seq(0, 1, 0.1),expand=c(0,0)) + scale_x_continuous(breaks=seq(0, 8, 1)) + theme_bw() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_blank(),
  legend.position = c(0.9,0.85),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
```

```{r}
ggplot(data = subjectfinal,aes(x=m,y=sub_judge)) + geom_point(size=2) + geom_line(size=1) + ylab("Probability of being judged as human") + xlab("Value of parameter m")+ coord_cartesian(xlim=c(0,8),ylim=c(0, 1)) + scale_y_continuous(breaks=seq(0, 1, 0.1),expand=c(0,0)) + scale_x_continuous(breaks=seq(0, 8, 1)) + theme_bw() + facet_wrap(~Sub) + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_blank(),
  legend.position = c(0.9,0.85),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
```