---
title: "Exp3"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(Rcmdr)
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
library(lsr)
library(pwr)
```

```{r}
subs <- dir(path = "./Exp3")
datfinal <- data.frame()
for (i in 1:length(subs))
{
  tps <- dir(path = paste0("./Exp3/",subs[i]))
  tps <- mixedsort(tps)
  for (j in 1:length(tps))
  {
    dat <- read.table(paste0("./Exp3/",subs[i],"/",tps[j]), header=FALSE, sep="_", na.strings="NA", dec=".", strip.white=TRUE)
    dat <- dat[2:nrow(dat),]
    M <- dat[,c(2,3)]
    M2 <- M[which(M[,1]>=250),]
    datfinal <- rbind(datfinal,list(i,dat[1,1],M2[1,2]))
  }
}
names(datfinal) <- c("Sub","Angle","LR")
datfinal$LR[datfinal$LR<0] <- 0
datfinal$LR[datfinal$LR>0] <- 1
datfinal$Sub <- as.factor(datfinal$Sub)
temp <- ddply(datfinal,c("Sub","Angle"),summarise,pp=mean(LR))
all <- ddply(temp,"Angle",summarise,P=mean(pp),P_SE=sd(pp)/sqrt(length(subs)))
```

```{r}
fit2 <- ddply(datfinal,c("Sub","Angle"),summarize,P=mean(LR))
fit2_1 <- subset(fit2,Angle==0)
fit2_2 <- subset(fit2,Angle==1)
model <- t.test(fit2_1$P,fit2_2$P,paired = TRUE)
es <- cohensD(x=fit2_1$P,y=fit2_2$P,method="paired")
```

```{r line comparison}
comp <- readXL("./Exp13comp.xlsx", rownames=FALSE, 
  header=TRUE, na="", sheet="Sheet1", stringsAsFactors=FALSE)
comp$LR[comp$LR=="Left"] <- 150
comp$LR[comp$LR=="Right"] <- 30
comp$LR <- as.numeric(comp$LR)
ggplot(data = comp,aes(x=LR,y=P,group=Type)) + geom_point(size=1.5) + geom_line(aes(linetype=Type),size=0.5) + geom_errorbar(aes(ymin=P-P_SE, ymax=P+P_SE), width=8,size=0.5) + ylab("Probability of bypassing from right") + xlab("Body orientation of the virtual human (°)")+ coord_cartesian(ylim=c(0, 1),xlim = c(0,180)) + scale_y_continuous(breaks=seq(0, 1, 0.2),expand=c(0,0)) + scale_x_continuous(breaks=seq(0, 180, 30),expand = c(0,0)) + theme_classic() + theme(axis.title = element_text(size=8, colour="black"),
  axis.text  = element_text(size=6, colour="black"),
  axis.line = element_line(size=0.25),
  axis.ticks = element_line(size=0.25),
  legend.position = "none",
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
```
