---
title: "Exp7-2"
output: html_document
---

```{r setup, include=FALSE}
library(Rcmdr)
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
library(zoo)
library(pracma)
library(ggsignif)
library(magrittr)
library(gganimate)
```

```{r}
subs <- dir(path = "./Exp7/Session2/FreeWalkData")
subs <- mixedsort(subs)
freewalkspeed <- data.frame()
for (i in 1:length(subs))
{
  DatFreeWalk <- read.table(paste0("./Exp7/Session2/FreeWalkData/",subs[i]), header = FALSE, sep = ";", na.strings = "NA",dec = ".", strip.white = TRUE)
  DatFreeWalk$V3 <- as.numeric(gsub(",","",DatFreeWalk$V3))
  DatFreeWalk <- DatFreeWalk[which(DatFreeWalk$V1>5),]
  DatFreeWalk$V3[which(DatFreeWalk$V1 %% 2 == 0)] <- (DatFreeWalk$V3[which(DatFreeWalk$V1 %% 2 == 0)] - 1300)*-1
  DatFreeWalk <- DatFreeWalk[which(DatFreeWalk$V3 > 300),]
  DatFreeWalk <- DatFreeWalk[which(DatFreeWalk$V3 < 800),]
  WalkTime <- 0
  for (trial in 6:15)
  {
    SubFreeWalk <- DatFreeWalk[which(DatFreeWalk$V1 == trial),2]
    rows <- length(SubFreeWalk)
    WalkTime <- WalkTime + SubFreeWalk[rows] - SubFreeWalk[1]
  }
  subspeed <- 5000/WalkTime
  freewalkspeed <- rbind(freewalkspeed,subspeed)
}
```

```{r}
trialnum <- 150
datall <- data.frame()
datfinal <- data.frame()
for (i in 1:length(subs))
{
  dat <- read.table(paste0("./Exp7/Session2/Data/",subs[i]), header = FALSE, sep = ";", na.strings = "NA", dec = ".", strip.white = TRUE)
  dat$V6 <- as.numeric(gsub(",","",dat$V6))
  dat$V12 <- as.numeric(gsub(",","",dat$V12))
  dat$V13 <- as.numeric(gsub(",","",dat$V13))  
  dat$V6[which(dat$V1 %% 2==1)] <- (dat$V6[which(dat$V1 %% 2==1)] - 1300) * -1
  dat$V7[which(dat$V1 %% 2==1)] <- dat$V7[which(dat$V1 %% 2==1)] * -1
  dat$V12[which(dat$V1 %% 2==1)] <-  (dat$V12[which(dat$V1 %% 2==1)] - 1300) * -1
  dat$V13[which(dat$V1 %% 2==1)] <- dat$V13[which(dat$V1 %% 2==1)] * -1
  for (j in 1:trialnum) 
  {
    temp <- dat[which(dat$V1==j),c(1:8,12:13)]
    temp <- temp[which(temp$V12>-10000),]
    temp <- temp[which(temp$V6>temp$V12),]
    if (nrow(temp) == 0)
    {
      next
    }
    if (temp[1,7]>temp[1,10])
    {
      datfinal <- rbind(datfinal,c(i,j,temp[1,3],temp[1,4],temp[1,5],1))
    }else{
      datfinal <- rbind(datfinal,c(i,j,temp[1,3],temp[1,4],temp[1,5],0))
    }
  }
}
names(datfinal) <- c("Sub","Trial","Pos","Speed","Avatar","LR")
subjectfinal <- ddply(datfinal,.(Sub,Pos,Speed),summarise,ratio = mean(LR))
final <- ddply(subjectfinal,.(Pos,Speed),summarise,p = mean(ratio),se = sd(ratio)/sqrt(length(subs)))
final$Pos <- final$Pos*30-90
final2 <- final
final2$p[final2$Pos<0] <- 1-final2$p[final2$Pos<0]
write.table(final,file = "final.csv",row.names = FALSE,col.names = FALSE,sep = ",")
final$Speed <- as.factor(final$Speed)
final$Pos <- as.factor(final$Pos)
final2$Speed <- as.factor(final2$Speed)
final2$Pos <- as.factor(final2$Pos)
```

```{r}
sta <- subjectfinal
sta$Pos <- as.factor(sta$Pos)
sta$Speed <- as.factor(sta$Speed)
sta$Sub <- as.factor(sta$Sub)
fit <- ezANOVA(data = sta,
               dv = ratio,
               wid = Sub,
               within = .(Pos,Speed))
print(fit)
```

```{r line}
ggplot(data = final,aes(x=Pos,y=p,group=Speed)) + geom_line(aes(colour=Speed),size=1) + geom_point(aes(colour=Speed),size=3) + geom_errorbar(aes(ymin=p-se, ymax=p+se,colour=Speed), width=0.1,size=1) + ylab("Probability of bypassing from right side") + xlab("Starting position of the virtual human (°)" )+ coord_cartesian(ylim=c(0, 1)) + scale_y_continuous(breaks=seq(0, 1, 0.1),expand=c(0,0)) + scale_x_discrete(breaks=seq(-60,60,30)) + theme_bw() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = "top",
  legend.key.width = unit(15,"mm"),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm")) + scale_color_brewer(name="Speed",palette = "Set2")
```

```{r line right side model}
datcor <- read.table("./corD.csv",
   header=FALSE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
names(datcor) <- c("data","model")
final3 <- final
final3$p <- 1/(1+exp(4.357-4.478*datcor$model))
final3$se <- 0
# final3[1:6,3] <- 1-final3[1:6,3]
final$Type <- "Experimental Data"
final3$Type <- "Model Prediction"
finalmodel <- rbind(final,final3)

ggplot(data = finalmodel,aes(x=Pos,y=p,color=Speed,linetype=Type,shape=Type,group=interaction(Speed,Type))) + geom_line(size=1) + geom_point(size=4.5) + geom_errorbar(aes(ymin=p-se, ymax=p+se), width=0.1,size=1) + ylab("Probability of bypassing from right") + xlab("Starting position of the virtual human (°)" )+ coord_cartesian(ylim=c(0, 1)) + scale_y_continuous(breaks=seq(0, 1, 0.2),expand=c(0,0)) + scale_x_discrete(breaks=seq(-60,60,30))+ guides(fill=guide_legend(title='MY NEW TITLE')) + theme_classic() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=12, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=12, colour="black"),
  legend.title = element_blank(),
  legend.position = "top",
  legend.key.width = unit(15,"mm"),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm")) + scale_color_brewer(name="Speed",palette = "Set2")
```
