---
title: "Exp7"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(Rcmdr)
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
library(extrafont)
```

```{r}
trialnum <- 150
subs <- dir(path = "./Exp7")
subs <- mixedsort(subs)
datall <- data.frame()
datfinal <- data.frame()
for (i in 1:length(subs))
{
  dat <- read.table(paste0("./Exp7/",subs[i]), header=FALSE, sep=";", na.strings="NA", dec=".", strip.white=TRUE)
  dat <- cbind(rep(i,nrow(dat)),dat)
  dat$V8[which(dat$V1 %% 2==0)] <- (dat$V8[which(dat$V1 %% 2==0)] - 500) * -1
  dat$V9[which(dat$V1 %% 2==0)] <- dat$V9[which(dat$V1 %% 2==0)] * -1
  dat$V9[which(dat$V5==0)] <- dat$V9[which(dat$V5==0)] * -1
  datall <- rbind(datall,dat)
  for (j in 1:trialnum)
  {
    temp <- subset(dat,V1==j)
    temp <- subset(temp,V8>250)
    datfinal <- rbind(datfinal,list(i,temp[1,4],temp[1,5],temp[1,7],temp[1,8],temp[1,10]))
  }
}
names(datall) <- c("Sub","Trial","Time","LD","IPD","LR","L_Avatar","R_Avatar","X","Y","Z","RotX","RotY","RotZ")
names(datfinal) <- c("Sub","LD","IPD","L_Avatar","R_Avatar","Dis")
datall$Sub <- as.factor(datall$Sub)
datall$LD <- as.factor(datall$LD)
datall$IPD <- as.factor(datall$IPD)
results <- datfinal[which(datfinal$Dis <= datfinal$LD + datfinal$IPD),]
finalresults <- results
finalresults$Dis[which(results$Dis > results$LD)] <- 1
finalresults$Dis[which(results$Dis < results$LD)] <- 0
subjectfinal <- ddply(finalresults,c("Sub","LD","IPD"),summarise,ratio = mean(Dis))
finaldata <- ddply(subjectfinal,c("LD","IPD"),summarise,p = mean(ratio),se = sd(ratio)/sqrt(length(subs)))
write.table(finaldata,file = "Selection_Data.csv",row.names = FALSE,col.names = FALSE,sep = ",")
finaldata$IPD[finaldata$IPD==200] <- "2 m"
finaldata$IPD[finaldata$IPD==300] <- "3 m"
finaldata$IPD[finaldata$IPD==400] <- "4 m"
finaldata$IPD <- as.factor(finaldata$IPD)
```

```{r}
sta <- subjectfinal
sta$LD <- as.factor(sta$LD)
sta$IPD <- as.factor(sta$IPD)
sta$Sub <- as.factor(sta$Sub)
fit <- ezANOVA(data = sta,
               dv = ratio,
               wid = Sub,
               within = .(LD,IPD))
print(fit)
```

```{r linear correlation EnergyRatio}
datcor <- read.table("./corI.csv",
   header=FALSE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
names(datcor) <- c("data","model")
fit <- lm(datcor$data~datcor$model)
summary(fit)
```

```{r linear correlation PathRatio}
datcor <- read.table("./corIP.csv",
   header=FALSE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
names(datcor) <- c("data","model")
fit <- lm(datcor$data~datcor$model)
summary(fit)

ggplot(data = datcor,aes(x=model,y=data)) + geom_point(size=2) + geom_smooth(colour="deepskyblue3",method = "glm", method.args = list(family = "binomial"), se = FALSE) + ylab("Probability of bypassing from right") + xlab("Model Prediction")+ coord_cartesian(ylim=c(-0.05, 1.05),xlim = c(0.94, 1.12)) + scale_y_continuous(breaks=seq(0, 1, 0.1),expand=c(0,0)) + scale_x_continuous(breaks=seq(0.94, 1.12, 0.02)) + theme_bw() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=13, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
# ggsave(file="Energy_Interaction_CorIP.pdf",width = 13, height = 10, units = "cm",useDingbats=FALSE)
```

```{r line length model prediction}
datcor <- read.table("./corIP.csv",
   header=FALSE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
names(datcor) <- c("data","model")
datcor$model <- 1/(1+exp(19.96-18.84*datcor$model))

predictgraph <- finaldata
predictgraph$Type <- "Experimental Data"
temp <- predictgraph
temp$p <- datcor$model
temp$se <- 0
temp$Type <- "Model Prediction"
predictgraph <- rbind(predictgraph,temp)

ggplot(data = predictgraph,aes(x=LD,y=p,group=interaction(IPD,Type))) + geom_line(aes(colour=IPD,linetype=Type),size=1,position = position_dodge(2)) + geom_point(aes(colour=IPD),size=3,position = position_dodge(2)) + geom_errorbar(aes(ymin=p-se, ymax=p+se,colour=IPD), width=7,size=1,position = position_dodge(2)) + ylab("Probability of bypassing from right") + xlab("Lateral Distance (cm)")+ coord_cartesian(ylim=c(0, 1)) + scale_y_continuous(breaks=seq(0, 1, 0.1),expand=c(0,0)) + scale_x_continuous(breaks=seq(-60, 20, 20)) + theme_bw() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.5),
  axis.ticks = element_line(size=0.5),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = c(0.88,0.8),
  legend.key.width = unit(15,"mm"),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm")) + scale_color_brewer(name="Interpersonal\nDistance",palette = "Set2")
ggsave("Energy_Interaction_lengthmodel.pdf",width = 20, height = 15, units = "cm",useDingbats=FALSE)
```